### ISSUE TITLE
template_fullpath is constructed but not used (read from template_path)

### ISSUE THREAD

**Issue by ikesyo** [motemen/git-pr-release#46]
https://github.com/motemen/git-pr-release/blob/985afbdcc4b8a4d9b68b9808cca2cfe4b1a7bc2d/lib/git/pr/release/util.rb#L91-L92

This is caused by #42.

**Comment by onk** [comment]
It is not intended! sorry :pray:
Find template file from the git root path is the correct behavior.

**Comment by ikesyo** [comment]
Thanks for the fix! ⚡️
